// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.CometFRC2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;


/**
 * This Group Command is used to drive the robot towards the left goal
 * turn towards it and shoot the ball in
 * 
 * @author Josh.Quintero@gmail.com (Joshua Quintero)
 */
public class AutoShootLeftSide extends CommandGroup {
    
    public  AutoShootLeftSide() {
       
        
        //Shoot ball
      //  addSequential(new FireSequence());
        //Drive Back 
      // addSequential(new DriveStraightToDistance(6,0.25,true)); 
        //Drive to Starting point
        addSequential(new DriveStraightToDistance(36,0.25,false)); 
        //Shoot Second ball
        addSequential(new FireSequence());
        //delay-1 (??)
     //   addSequential(new WaitCommand(1));
        //Drive to END
      // addSequential(new DriveStraightToDistance(24,0.25,true)); 
        // Wait 0.5 seconds to allow drive to settle
        //addSequential(new WaitCommand(5));
        // Turn 12 inches at 25% power, in the left directions to face left goal
        //addSequential(new Turn(48,0.6,false));
        // Wait 0.5 seconds to allow drive to settle
      //  addSequential(new WaitCommand(0.5));
        // Cock Catapult to get ready to shoot
       // addSequential(new CockCatapult());
        // Shoot the ball
       // addSequential(new ShootCatapult());
     
    }
}
