// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.CometFRC2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousthreeBall extends CommandGroup {
    
    public  AutonomousthreeBall() {
         // Opens Intakes
        addSequential (new OpenIntakes());
        // Delay QUARTER of a second
        addSequential (new WaitCommand(0.25));
        // Fires 1st Ball
        addSequential (new ShootCatapult());
        // Cocks Catapult
        addSequential (new CockCatapult());
        // Brings in 2nd Ball
        addSequential (new BackRollerBringBallIn());
        // Delay HALF of a Second
        addSequential (new WaitCommand(0.25));
        //Shoots 2nd Ball
        addSequential (new ShootCatapult());
        //Brings In 3rd Ball
        addSequential (new ExtendLimbs());
        // Cocks Catapult
        addSequential (new CockCatapult());
        // Drives Forward 2ft.
        addSequential (new DriveStraightToDistance(90.0,0.90,true));
        //Shoots 3rd Ball
        addSequential (new FireSequence());
    }
}
