// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.CometFRC2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This Group Command extends the front and back intake outwards
 * 
 * @author Josh.Quintero@gmail.com (Joshua Quintero)
 */
public class ExtendLimbs extends CommandGroup {
     
    public  ExtendLimbs() {
        
        // The two commands are called at the same time to extend outward the 
        // intakes. It can be used to get ready to catch the ball
        //addParallel(new FrontTiltForward());
        //addParallel(new BackTiltForward());
         addSequential(new BackTiltSetOutward());
         addSequential(new FrontTiltSetOutward());
         addSequential(new WaitCommand(0.25));
         addSequential(new BackRollerBringBallIn());
         addSequential(new FrontRollerBringBallIn());
         
        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
