// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.CometFRC2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This Command Group calls other commands to retract both the front and 
 * back intakes. This can be used to catch the ball.
 *
 * @author Josh.Quintero@gmail.com (Joshua Quintero)
 */
public class RetractLimbs extends CommandGroup {
    
    public  RetractLimbs() {
        //Stop Intake Rollers
        //Retract the front and back intakes inward
       // addParallel(new FrontTiltBack());
        //addParallel(new BackTiltBack());
        addSequential(new BackRollerStop());
        addSequential(new FrontRollerStop());
        addSequential(new FrontTiltSetInward());
        addSequential(new BackTiltSetInward());
        
        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
